### ISSUE TITLE
Solution for "ImportError: No module named lxml" on Mac

### ISSUE THREAD

**Issue by dueddel** [berteh/svg-objects-export#10]
Some users may get the mentioned error above when using the terminal of Mac OS.

It's fixed easily as I could find here: http://stackoverflow.com/questions/22674730/importerror-no-module-named-lxml-on-mac#22692262

&rarr; As a developer you might have installed XCode previously. In that case you *only* have to enter the following two commands into your terminal:

<code>sudo easy_install pip</code>
<code>sudo pip install lxml</code>

(Yes, <code>sudo</code> is required.) That takes a few seconds and BAM! It works (at least it did for me).

For more details click the posted link.

---

By the way, this one is a great script, @berteh! Helped me out on playing around a bit. Thanks a lot!

**Comment by berteh** [comment]
Thanks for the note @dueddel.

**Comment by dredenba** [comment]
perfect just what I was looking for

**Comment by berteh** [comment]
added to project documentation.
