### ISSUE TITLE
Canvas isn't resized properly for PDF and PS exports

### ISSUE THREAD

**Issue by bertob** [berteh/svg-objects-export#12]
When exporting objects as PDF and PS, the output files have the same canvas size as the original SVG document, instead of the object size.
When I export the exact same objects as PNG or EPS everything works as expected.
This is the command I ran:

```
python2.7 svg-objects-export.py -t pdf test.svg
```

This is the file I used for testing: https://gist.github.com/bertob/649f3d69a3720f1b5c2a
Here's a screenshot of the results I get: http://imgur.com/RhbaZOk

I'm using Arch GNU/Linux, Inkscape 0.91 r13725 and Python 2.7.9

Am I missing something?
Could this be because of the Inkscape version I'm using?

**Comment by berteh** [comment]
Hello bertob.
This behaviour is the default by Inkscape... that the script does not actually change.

It is described in [command line export documentation](http://docs.huihoo.com/inkscape/guide-2nd/html/CommandLine-Export.html) and [changelogs](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.47#PDF.2C_PostScript.2C_and_EPS_export). In short: 

> By default, Inkscape sets the BoundingBox to the page area for PS [and PDF] files and to the drawing bounding box for EPS files (both at 72 dpi).

So an option is to export to eps then run epstopdf, or use inkscape's parameters ``--export-area-canvas`` or ``--export-area-drawing``. The line below works to export only the objects in pdf... but still the exported elements' bounding box seems off in pdf export for "two" and "three"... resulting in a misplaced rectangle (center of box is too right & low).  Kindly [contact the inkscape guys](https://bugs.launchpad.net/inkscape) to ask for a fix ;)

    svg-objects-export -D -t pdf --extra '--export-area-drawing ' test.svg

**Comment by bertob** [comment]
Yeah, I had found the `--export-aera-drawing` option myself yesterday, it seems like they change the default behavior in 0.91, because in 0.48 the bounding boxes are correct.

I'll definitely try to contact upstream about this, but in the mean time I think it would be good to ensure consistent behavior when using the script, regardless of what inkscape's defaults are.

Do you think simply adding `--export-aera-drawing` to every executed inkscape command would be ok or is that too hacky? I've tried it myself and haven't run into any problems yet, if you want I can submit a PR.

**Comment by berteh** [comment]
Hi bertob.
I'd rather not add this as the default option for pdf... because then there would be no way to actually remove it on purpose (it would "hardcoded"). But I agree that would be more intuitive...
