### ISSUE TITLE
is there a way to export with 16-bit depth?

### ISSUE THREAD

**Issue by iszotic** [berteh/svg-objects-export#18]
Hi, I know it's kind of edgy to ask, because only the development version of inkscape has the option for exporting with 16-bit per channel, but maybe there's a command line hack. I do textures for 3D models with inkscape that's why I want to know how to export to 16-bit because with 8-bit the textures get jagged because of the quantization of gradients. Thanks

**Comment by berteh** [comment]
maybe... did you already have a look at ``inkscape --verb-list`` of this development version of yours, to see if any verb already exists to allow that?

**Comment by berteh** [comment]
in short: if inkscape allows it, this script does too. If Inkscape does not either send a patch to Inkscape guys, or ask them nicely ;)
