### ISSUE TITLE
Bugs n status about using this tool in 2018 on Windows 10

### ISSUE THREAD

**Issue by SuperKLA** [berteh/svg-objects-export#19]
I recently used this tool and here are my issues.

1) I have an empty space in the infile arg so that the passed argument in the command line can not work.
To reproduce just create a svg file, paste it into a folder with an empty space in it and bingo.

2) I use plane-svg to export and the output tells me something like this. 
![image](https://user-images.githubusercontent.com/17930543/48486243-41c52400-e81b-11e8-8862-6044610fd20c.png). I changed the code to remove the double dot.

Here you can see my changes
![image](https://user-images.githubusercontent.com/17930543/48486434-cc0d8800-e81b-11e8-99ef-f74aece0916e.png)

By the way, some things can be misleading.

- the .bat only works under specific circumstances, e.g. Path , Location needs to be correct, may be advise the user to check the file.
- Output files are generated in the inkscape program files folder, although it is possible to redirect it somewhere else (by using the .bat file), I expected the output near the input file.
- Hidden layers are exported correctly but invisible in the output, it is necessary to make them visible again (which is ok)

At the end it worked fine and saved me some time.

**Comment by berteh** [comment]
thanks for taking the time to report and improve. I integrated your suggestions.

**Comment by berteh** [comment]
as for your first item (white space) @SuperKLA , I'm no Windows specialist, but in Linux you need to escape the space (and a few other characters) by prepending them a backslash `\`. I guess it's similar in Win... or you could maybe use the old Win notation where `C:\Program Files` is represented as `C:\Progra~1`
