### ISSUE TITLE
Possible Inkscape cli updates

### ISSUE THREAD

**Issue by Spraynard** [berteh/svg-objects-export#23]
Downloaded Inkscape v1.0.1b and went to use this script when I came across `unknown option --export-png` error.

So, I then checked `Inkscape --help | grep png` and saw the following come up

```
  --export-type=[...]                        File type(s) to export: [svg,png,ps,eps,pdf,tex,emf,wmf,xaml]
  Export input files (in1.svg, in2.svg) to PNG format keeping original name (in1.png, in2.png):
	inkscape --export-type=png in1.svg in2.svg
```

I think that they might be deprecating `--export-png` and replacing it with `--export-type`.

Also notice that `--export-type` now accepts an `svg` input, instead of `plain-svg` input from before.

**Comment by berteh** [comment]
thanks for the issue report and (now merged) code improvement.

**Comment by Spraynard** [comment]
Of course thank you for making this script!
