### ISSUE TITLE
All objects output with plain-svg

### ISSUE THREAD

**Issue by alexrollin** [berteh/svg-objects-export#7]
I am only using plain-svg output. All exported files seem to be copies of the original file.

I am happy to use a pattern to try to narrow things down but I am not sure how to select "all objects that are groups, with an id that ends in "-24"" like -xpath "//svg:g[@inkscape:id=-24^]"

This is my current script:

vg-objects-export.py --force --type plain-svg --inkscape "C:/Progra~2/Inkscape/inkscape.exe" --destdir "C:/Users/myfolder/export/" tiny_test_file.svg

![2014-10-11_072600](https://cloud.githubusercontent.com/assets/114659/4600795/8d2092d8-50dd-11e4-97d2-d7c891c9f805.jpg)

**Comment by berteh** [comment]
That is a feature missing from Inkscape, as explained in #4, as soon as the Inkscape guys figure it out it will work with this script too.
