### ISSUE TITLE
Could not find inkscape command

### ISSUE THREAD

**Issue by ramunasjurgilas** [berteh/svg-objects-export#8]
After executing comment line: "svg-objects-export-master/svg-objects-export.py  UI/UI.svg" I am getting this error:
Could not find inkscape command line executable, set --inkscape option accordingly.
It is usually /usr/bin/inkscape in linux and C:\Progra~1\Inkscape\inkscape.com in windows.

In my case inkscape location is in this path: /Applications

Could you please give an advice what should be done to get rid of this error?

**Comment by berteh** [comment]
added to project doc. thanks.
