### ISSUE TITLE
How would I export grouped objects?

### ISSUE THREAD

**Issue by scottyu2012** [berteh/svg-objects-export#9]
I could export group objects in SVG using --pattern "^g" but then it exports the grouped object and its parts. 

Is there a way it could just do the grouped object and not its subparts?

The SVG is has \<g> and sub \<g> but I just want it to create object from first \<g>

**Comment by berteh** [comment]
Hello.

If you do not have many groups I would recommend changing their id (via ``object > property`` dialog in Inkscape) to something meaningful that does not start with 'g'... and you would be done (specifying no pattern on the tool command line exports only the objects with a changed id).


If finding the groups to export only based on their id is not possible, then the only option left is to use the [available xpath](http://effbot.org/zone/element-xpath.htm) support. Easier if you know your way around the xml representation of SVG (read on!)



If you can easily manage to put the groups to be exported on the same "depth" (eg: all the first groups in a layer, or all groups in groups in layers) then things are easy enough:

    svg-objects-export --xpath "/svg:svg/svg:g/svg:g/svg:g" -d depth3groups/ in.svg

It's easy too if you manage to group all the groups you want to export in a single group which ``id`` you can change:

    svg-objects-export --xpath "//svg:g[@id='parent-id']/svg:g" -d childrenOfParentID/ in.svg



But if you really need to cope for groups in all levels of depths it's a bit more complicated: you'll want to export all groups (``//svg:g``) with an id that starts with g (the Inkscape default, using [regular expressions](http://lxml.de/xpathxslt.html#regular-expressions-in-xpath) to filter them: ``[re:test(@id, '^g', 'i')]``), that have no direct parent group (``../../svg:g``) with a similar id, : 

    svg-objects-export --xpath "//svg:g[re:test(@id, '^g', 'i')][ not(../../svg:g[re:test(@id, '^g', 'i')]) ]" -d groupWithNoParentGroup/ in.svg


Hope this helps.
